# Convolution Transposed Exercise

torch.nn.ConvTranspose2d(in_channels, out_channels, kernel_size, stride=1, padding=0, output_padding=0, groups=1, bias=True, dilation=1)

check out https://github.com/vdumoulin/conv_arithmetic

## 1. Import Required Libraries

In [19]:
import torch
import torch.nn as nn
import torch.nn.init as init

## 2. Input Data

In [20]:
img = torch.ones(1,1,3,3)
print(img)

tensor([[[[ 1.,  1.,  1.],
          [ 1.,  1.,  1.],
          [ 1.,  1.,  1.]]]])


## 3. Set All Weights to One

In [21]:
transpose = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=0, output_padding=0, bias=False)
print(transpose.weight)

init.constant_(transpose.weight,1)

Parameter containing:
tensor([[[[-0.2439,  0.2455,  0.0076],
          [ 0.2158,  0.0300, -0.0415],
          [ 0.2713, -0.0479, -0.0554]]]])


Parameter containing:
tensor([[[[ 1.,  1.,  1.],
          [ 1.,  1.,  1.],
          [ 1.,  1.,  1.]]]])

## Kernel Size=3, stride=1, padding=0, output_padding=0

In [22]:
transpose(img)

tensor([[[[ 1.,  2.,  3.,  2.,  1.],
          [ 2.,  4.,  6.,  4.,  2.],
          [ 3.,  6.,  9.,  6.,  3.],
          [ 2.,  4.,  6.,  4.,  2.],
          [ 1.,  2.,  3.,  2.,  1.]]]])

## Kernel Size=3, stride=2, padding=0, output_padding=0

In [23]:
transpose = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=0, output_padding=0, bias=False)
init.constant_(transpose.weight,1)
transpose(img)

tensor([[[[ 1.,  1.,  2.,  1.,  2.,  1.,  1.],
          [ 1.,  1.,  2.,  1.,  2.,  1.,  1.],
          [ 2.,  2.,  4.,  2.,  4.,  2.,  2.],
          [ 1.,  1.,  2.,  1.,  2.,  1.,  1.],
          [ 2.,  2.,  4.,  2.,  4.,  2.,  2.],
          [ 1.,  1.,  2.,  1.,  2.,  1.,  1.],
          [ 1.,  1.,  2.,  1.,  2.,  1.,  1.]]]])

## Kernel Size=3, stride=2, padding=1, output_padding=0

In [24]:
transpose = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=1, output_padding=0, bias=False)
init.constant_(transpose.weight.data,1)
transpose(img)

tensor([[[[ 1.,  2.,  1.,  2.,  1.],
          [ 2.,  4.,  2.,  4.,  2.],
          [ 1.,  2.,  1.,  2.,  1.],
          [ 2.,  4.,  2.,  4.,  2.],
          [ 1.,  2.,  1.,  2.,  1.]]]])

## Kernel Size=3, stride=2, padding=0, output_padding=1

In [25]:
transpose = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=0, output_padding=1, bias=False)
init.constant_(transpose.weight.data,1)
transpose(img)

tensor([[[[ 1.,  1.,  2.,  1.,  2.,  1.,  1.,  0.],
          [ 1.,  1.,  2.,  1.,  2.,  1.,  1.,  0.],
          [ 2.,  2.,  4.,  2.,  4.,  2.,  2.,  0.],
          [ 1.,  1.,  2.,  1.,  2.,  1.,  1.,  0.],
          [ 2.,  2.,  4.,  2.,  4.,  2.,  2.,  0.],
          [ 1.,  1.,  2.,  1.,  2.,  1.,  1.,  0.],
          [ 1.,  1.,  2.,  1.,  2.,  1.,  1.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

## Kernel Size=3, stride=2, padding=1, output_padding=1

In [26]:
transpose = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=1, output_padding=1, bias=False)
init.constant_(transpose.weight.data,1)
transpose(img)

tensor([[[[ 1.,  2.,  1.,  2.,  1.,  1.],
          [ 2.,  4.,  2.,  4.,  2.,  2.],
          [ 1.,  2.,  1.,  2.,  1.,  1.],
          [ 2.,  4.,  2.,  4.,  2.,  2.],
          [ 1.,  2.,  1.,  2.,  1.,  1.],
          [ 1.,  2.,  1.,  2.,  1.,  1.]]]])