# Convolution Transposed Exercise

torch.nn.ConvTranspose2d(in_channels, out_channels, kernel_size, stride=1, padding=0, output_padding=0, groups=1, bias=True, dilation=1)

check out https://github.com/vdumoulin/conv_arithmetic

## 1. Import Required Libraries

In [6]:
import torch
import torch.nn as nn
import torch.nn.init as init

## 2. Input Data

In [7]:
img = torch.ones(1,1,3,3)
print(img)

tensor([[[[ 1.,  1.,  1.],
          [ 1.,  1.,  1.],
          [ 1.,  1.,  1.]]]])


## 3. Set All Weights to One

In [8]:
transpose = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=0, output_padding=0, bias=False)
print(transpose.weight)

init.constant_(transpose.weight,1)

Parameter containing:
tensor([[[[ 0.0206, -0.1985, -0.3008],
          [ 0.1443,  0.1907, -0.2587],
          [-0.2740,  0.0397, -0.1210]]]])


Parameter containing:
tensor([[[[ 1.,  1.,  1.],
          [ 1.,  1.,  1.],
          [ 1.,  1.,  1.]]]])

## Kernel Size=3, stride=1, padding=0, output_padding=0

In [9]:
transpose(img)

tensor([[[[ 1.,  2.,  3.,  2.,  1.],
          [ 2.,  4.,  6.,  4.,  2.],
          [ 3.,  6.,  9.,  6.,  3.],
          [ 2.,  4.,  6.,  4.,  2.],
          [ 1.,  2.,  3.,  2.,  1.]]]])

## Kernel Size=3, stride=2, padding=0, output_padding=0

In [10]:
transpose = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=0, output_padding=0, bias=False)
init.constant_(transpose.weight,1)
transpose(img)

tensor([[[[ 1.,  1.,  2.,  1.,  2.,  1.,  1.],
          [ 1.,  1.,  2.,  1.,  2.,  1.,  1.],
          [ 2.,  2.,  4.,  2.,  4.,  2.,  2.],
          [ 1.,  1.,  2.,  1.,  2.,  1.,  1.],
          [ 2.,  2.,  4.,  2.,  4.,  2.,  2.],
          [ 1.,  1.,  2.,  1.,  2.,  1.,  1.],
          [ 1.,  1.,  2.,  1.,  2.,  1.,  1.]]]])

## Kernel Size=3, stride=2, padding=1, output_padding=0

In [11]:
transpose = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=1, output_padding=0, bias=False)
init.constant_(transpose.weight.data,1)
transpose(img)

tensor([[[[ 1.,  2.,  1.,  2.,  1.],
          [ 2.,  4.,  2.,  4.,  2.],
          [ 1.,  2.,  1.,  2.,  1.],
          [ 2.,  4.,  2.,  4.,  2.],
          [ 1.,  2.,  1.,  2.,  1.]]]])

## Kernel Size=3, stride=2, padding=0, output_padding=1

In [12]:
transpose = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=0, output_padding=1, bias=False)
init.constant_(transpose.weight.data,1)
transpose(img)

tensor([[[[ 1.,  1.,  2.,  1.,  2.,  1.,  1.,  0.],
          [ 1.,  1.,  2.,  1.,  2.,  1.,  1.,  0.],
          [ 2.,  2.,  4.,  2.,  4.,  2.,  2.,  0.],
          [ 1.,  1.,  2.,  1.,  2.,  1.,  1.,  0.],
          [ 2.,  2.,  4.,  2.,  4.,  2.,  2.,  0.],
          [ 1.,  1.,  2.,  1.,  2.,  1.,  1.,  0.],
          [ 1.,  1.,  2.,  1.,  2.,  1.,  1.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

## Kernel Size=3, stride=2, padding=1, output_padding=1

In [13]:
transpose = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=1, output_padding=1, bias=False)
init.constant_(transpose.weight.data,1)
transpose(img)

tensor([[[[ 1.,  2.,  1.,  2.,  1.,  1.],
          [ 2.,  4.,  2.,  4.,  2.,  2.],
          [ 1.,  2.,  1.,  2.,  1.,  1.],
          [ 2.,  4.,  2.,  4.,  2.,  2.],
          [ 1.,  2.,  1.,  2.,  1.,  1.],
          [ 1.,  2.,  1.,  2.,  1.,  1.]]]])